### ISSUE TITLE
[Bug] Plugman does not work with latest version of Cordova iOS (5.0.1)

### ISSUE THREAD

**Issue by willmero** [apache/cordova-plugman#126]
# Bug Report

## Problem
Plugman does not work with latest version of Cordova iOS (5.0.1), resulting in error:
`Failed to install 'cordova-plugin-background-fetch': Error: Your ios platform does not have Api.js`
When running:
`plugman install --platform ios --project platforms/ios --plugin cordova-background-geolocation-lt`

### What is expected to happen?
The plugin will install to this specific platform correctly

### What does actually happen?
Fails with error:
`Failed to install 'cordova-plugin-background-fetch': Error: Your ios platform does not have Api.js`

## Information

Cordova Version 9.0.0
Cordova iOS version 5.0.1
Plugman version: Latest (unable to check using plugman --version)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Does this also happen with other plugins?
In what context and what for are you using plugman?

**Comment by willmero** [comment]
Yes this does happen with other plugins, and I am looking to install a specific plugin onto just iOS as the functionality I am looking for only works on the iOS platform for the above plugin. I have another android library to fill the need on the android platform that is separate.

**Comment by janpio** [comment]
Can you help me reproduce this error? Best start with `cordova create` and then list all the commands necessary to reproduce this. Thanks.

**Comment by IanTheLeader** [comment]
Having this same issue as OP with plugman and iOS 5.0.1

**Comment by janpio** [comment]
The you can help us by doing the same things I asked with the command above.

**Comment by pedroadame** [comment]
Bump. Install failing using plugman to install cordova-plugin-iosrtc just for iOS platform. cordova-ios@6.2.0 plugman@3.0.1

**Comment by erisu** [comment]
Closing this ticket as staleness.

Janpio asked twice in the past for steps to help him reproduce the issue so that we could have a starting point but no one was able to provide us this information.

I created a project, added the iOS platform, and ran the plugman command with no issues.

```
$ plugman install --platform ios --project platforms/ios --plugin cordova-background-geolocation-lt
Installing "cordova-background-geolocation-lt" for ios
Installing "cordova-plugin-background-fetch" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
```

We can reopen the ticket once someone can provide us with steps that reproduce this issue.
